SUBROUTINE write_header(ntuvonline)
!------------------------------------------------------------------------

!     -- DESCRIPTION

!     Write headers of subroutines

!     FEXCHEM.F    : chemical production terms (P-Lc).
!     JACDCHEMDC.F : Jacobian Matrix (d/dc(P-Lc)).
!     KINETIC.F    : kinetic rate k.
!     RATES.F      : reaction rates w.
!     DRATEDC.F    : derivatives dw/dc.
!     FEXPROD.F    : production terms P.
!     FEXLOSS.F    : loss terms L.
!------------------------------------------------------------------------

!     -- INPUT VARIABLES

!     -- INPUT/OUTPUT VARIABLES

!     -- OUTPUT VARIABLES

!------------------------------------------------------------------------

!     -- REMARKS

!     Label 300: blank line.
!     Label 150: comments.
!     Label 200: C-------...
!------------------------------------------------------------------------

!     -- MODIFICATIONS

!------------------------------------------------------------------------

!     -- AUTHOR(S)

!     Bruno Sportisse, CEREA, 2003.

!------------------------------------------------------------------------
IMPLICIT NONE
INCLUDE 'nficfort'
INCLUDE 'parametre'

INTEGER, INTENT(IN)                  :: ntuvonline

INTEGER :: nwrite

!------------------------------------------------------------------------------------------------

!     Routine kinetic.f90
nfick=ipiste
ipiste=ipiste+1
OPEN(nfick,FILE='chem_spack_kinetic.f90',STATUS='new')
nwrite=nfick

!srf - for modules format
WRITE(nwrite,6701)
6701  FORMAT(1X,'MODULE mod_chem_spack_kinetic')
WRITE(nwrite,FMT='(A)') '  '
write(nwrite,6003)
WRITE(nwrite,6004)
WRITE(nwrite,6705)
6705 FORMAT(3X,'PUBLIC :: kinetic ! subroutine')
WRITE(nwrite,6006)
!srf- sempre colocar cosz no argumento rotina kinetic para man
WRITE(nwrite,401)

401  FORMAT(3X,'SUBROUTINE kinetic(jppj,Jphoto,rk,temp,xlw,Press,cosz,att,ijkbeg,ijkend,maxblock_size,nr)')

WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,402)
402  FORMAT('!',5X,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,403)
403  FORMAT('!',5X,'This routine computes the kinetic rates',  &
    ' for the gas-phase.')
WRITE(nwrite,404)
404  FORMAT('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
250  FORMAT('!     Mechanism: ',a20)
251  FORMAT('!     Species: ',a20)
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,405)
405  FORMAT('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,406)
406  FORMAT('!     TEMP: temperature ([K]).')
WRITE(nwrite,407)
407  FORMAT('!     XLW: water massic fraction.')
WRITE(nwrite,408)
408  FORMAT('!     PRESS: pressure ([Pa]).')
IF(ntuvonline == 0) WRITE(nwrite,409)
409  FORMAT('!     AZI: zenithal angle ([degree]).')
WRITE(nwrite,410)
410  FORMAT('!     ATT: attenuation variable.')
WRITE(nwrite,150)
WRITE(nwrite,413)
413  FORMAT('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,414)
414  FORMAT('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,415)
415  FORMAT('!     RK: kinetic rates.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,416)
416  FORMAT('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,417)
417  FORMAT('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,418)
418  FORMAT('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,419)
419  FORMAT('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
!srf- nr is now passed via argument of the command call
!WRITE(nwrite,FMT='(A)') '  USE chem1_list, ONLY: nr'
WRITE(nwrite,300)
      write(nwrite,420)
420  FORMAT('      IMPLICIT NONE')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: jppj,ijkbeg,ijkend,maxblock_size,nr'
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN) ::  xlw(maxblock_size),att(maxblock_size),cosz(maxblock_size)'
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN) ::  temp(maxblock_size),Press(maxblock_size)'
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(OUT) ::  rk(maxblock_size,nr)'

IF(ntuvonline == 0) THEN
  WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) ::  Effko,Rapk,facteur'
  WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) :: YlH2O,SumM,azi'
  WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN) ::  Jphoto(maxblock_size,jppj)'
ELSE
  WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) ::  Effko,Rapk,facteur'
  WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,DIMENSION(maxblock_size) :: YlH2O,SumM,azi'
  WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN) ::  Jphoto(maxblock_size,jppj)'
END IF
WRITE(nwrite,FMT='(A)') '      INTEGER :: ijk'

WRITE(nwrite,300)
WRITE(nwrite,438)
438  FORMAT('!     Compute third body.')
WRITE(nwrite,439)
439  FORMAT('!     Conversion = Avogadro*1d-6/Perfect gas constant.')
WRITE(nwrite,440)
440  FORMAT('!     PRESS in Pascal, SUMM in molecules/cm3,',  &
    ' TEMP in Kelvin')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbeg,ijkend'
WRITE(nwrite,FMT='(A)') '        SumM(ijk) = Press(ijk) * 7.243D16 / temp(ijk)'
WRITE(nwrite,FMT='(A)') '      END DO'
WRITE(nwrite,300)
WRITE(nwrite,442)
442  FORMAT('!     Number of water molecules computed from',  &
    ' the massic fraction')
WRITE(nwrite,443)
443  FORMAT('!     (absolute humidity)')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbeg,ijkend'
WRITE(nwrite,FMT='(A)') '         YlH2O(ijk) = 29.d0*SumM(ijk)*xlw(ijk)/(18.d0+11.d0*xlw(ijk))'
WRITE(nwrite,FMT='(A)') '      END DO'
WRITE(nwrite,300)
WRITE(nwrite,445)
445  FORMAT('!     For the zenithal angle at tropics')
WRITE(nwrite,300)
IF(ntuvonline == 0) WRITE(nwrite,446)
446  FORMAT('      azi=abs(acos(cosz)*180.0/3.1415926) !From cosz obtain angle azi in degrees')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '       DO ijk=ijkbeg,ijkend'


!------------------------------------------------------------------------------------------------
!     Routine fexchem.f90
nficf=ipiste
ipiste=ipiste+1
OPEN(nficf,FILE='chem_spack_fexchem.f90',STATUS='new')
nwrite=nficf
WRITE(nwrite,FMT='(A)') '  '
!srf - for modules format
WRITE(nwrite,6501)
6501  FORMAT(1X,'MODULE mod_chem_spack_fexchem')
WRITE(nwrite,FMT='(A)') '  '
WRITE(nwrite,6502)
6502  FORMAT(3X,'USE mod_chem_spack_rates, ONLY: rates  ! subroutine')

write(nwrite,6003)
WRITE(nwrite,6004)
WRITE(nwrite,6505)
6505 FORMAT(3X,'PUBLIC :: fexchem ! subroutine')
WRITE(nwrite,6006)

WRITE(nwrite,FMT='(A)') '  '

WRITE(nwrite,501)
501  FORMAT(3X,'SUBROUTINE fexchem(y,rk,chem,ngas,ijkbegin,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,502)
502  FORMAT('!',5X,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,503)
503  FORMAT('!',5X,'This routine computes the chemical production', ' term.')
WRITE(nwrite,504)
504  FORMAT('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,505)
505  FORMAT('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,506)
506  FORMAT('!     Y: chemical concentrations.')
WRITE(nwrite,415)
!     415  format('!     RK: kinetic rates.')
507  FORMAT('!     W: reaction rates.')
WRITE(nwrite,508)
508  FORMAT('!     ZCSOURC: volumic emissions.')
WRITE(nwrite,150)
WRITE(nwrite,513)
513  FORMAT('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,514)
514  FORMAT('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,515)
515  FORMAT('!     CHEM: array of chemical production terms.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,516)
516  FORMAT('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,517)
517  FORMAT('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,518)
518  FORMAT('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,519)
519  FORMAT('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '       IMPLICIT NONE'
WRITE(nwrite,300)
WRITE(nwrite,300)

!WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: ngas,ijkbegin,ijkend,maxblock_size,nr'
!WRITE(nwrite,FMT='(A)') '      LOGICAL,INTENT(IN) :: lsourc !Volumic source terms'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN)  :: rk(maxblock_size,nr)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN)  :: y(maxblock_size,ngas)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN)  :: ZCsourc(maxblock_size,NGAS)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(OUT) :: chem(maxblock_size,NGAS)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION :: w(maxblock_size,nr)'
!WRITE(nwrite,FMT='(A)') '      INTEGER ::  i,ijk'

WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ngas                    '
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ijkbegin		 '
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ijkend 		 '
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: maxblock_size		 '
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: nr		  	 '
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)	 '    
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,ngas)   '    
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(OUT) :: chem(maxblock_size,NGAS)'    
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION :: w(maxblock_size,nr)			 '   
WRITE(nwrite,FMT='(A)') '      INTEGER ::  ijk						 '   


WRITE(nwrite,300)
WRITE(nwrite,539)
539  FORMAT('       chem=0.d0')
WRITE(nwrite,300)
WRITE(nwrite,541)
541  FORMAT('!     Compute reaction rates.')
WRITE(nwrite,300)
WRITE(nwrite,542)
542  FORMAT('      call rates(rk,y,w,ngas,ijkbegin,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,543)
543  FORMAT('!     Chemical production terms.')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbegin,ijkend'




!------------------------------------------------------------------------------------------------
!     Routine jacdchemdc.f90
nficj=ipiste
ipiste=ipiste+1
OPEN(nficj,FILE='chem_spack_jacdchemdc.f90',STATUS='new')
nwrite=nficj
WRITE(nwrite,FMT='(A)') '  '

!srf - for modules format
WRITE(nwrite,6001)
6001  FORMAT(1X,'MODULE mod_chem_spack_jacdchemdc')
WRITE(nwrite,FMT='(A)') '  '
WRITE(nwrite,6002)
6002  FORMAT(3X,'USE mod_chem_spack_dratedc, ONLY: dratedc  ! subroutine')
write(nwrite,6003)
6003  FORMAT(3X,'IMPLICIT NONE')
WRITE(nwrite,6004)
6004 FORMAT(3X,'PRIVATE')
WRITE(nwrite,6005)
6005 FORMAT(3X,'PUBLIC :: jacdchemdc ! subroutine')
WRITE(nwrite,6006)
6006 FORMAT(1X,'CONTAINS')
WRITE(nwrite,FMT='(A)') '  '

WRITE(nwrite,601)
601  FORMAT(3X,'SUBROUTINE jacdchemdc(y,rk,JacC,ngas,ijkbeg,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,602)
602  FORMAT('!',5X,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,603)
603  FORMAT('!',5X,'This routine computes the Jacobian matrix',  &
    ' for the gas-phase.')
WRITE(nwrite,604)
604  FORMAT('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,605)
605  FORMAT('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,606)
606  FORMAT('!     Y: chemical concentrations.')
WRITE(nwrite,415)
!     415  format('!     RK: kinetic rates.')
607  FORMAT('!     DW: derivative of reaction rates wrt Y.')
WRITE(nwrite,150)
WRITE(nwrite,613)
613  FORMAT('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,614)
614  FORMAT('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,615)
615  FORMAT('!     JACC: Jacobian matrix.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,616)
616  FORMAT('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,609)
609  FORMAT('!     The matrix JACC could be stored in a ',  &
    'low-dimensional vector.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,617)
617  FORMAT('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,618)
618  FORMAT('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,619)
619  FORMAT('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,300)
write(nwrite,620)
620  FORMAT('      IMPLICIT NONE')
WRITE(nwrite,300)

WRITE(nwrite,300)
!WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: ngas,ijkbeg,ijkend,maxblock_size,nr' 
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(IN) :: rk(maxblock_size,nr),y(maxblock_size,NGAS)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(OUT) :: JacC(maxblock_size,NGAS,NGAS)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION :: dw(maxblock_size,nr,NGAS)'
!WRITE(nwrite,FMT='(A)') '      INTEGER :: i,j,ijk'


WRITE(nwrite,FMT='(A)') '       INTEGER 	 , INTENT(IN)  :: ngas                          ' 
WRITE(nwrite,FMT='(A)') '       INTEGER 	 , INTENT(IN)  :: ijkbeg			' 
WRITE(nwrite,FMT='(A)') '       INTEGER 	 , INTENT(IN)  :: ijkend			' 
WRITE(nwrite,FMT='(A)') '       INTEGER 	 , INTENT(IN)  :: maxblock_size 		' 
WRITE(nwrite,FMT='(A)') '       INTEGER 	 , INTENT(IN)  :: nr 				' 
WRITE(nwrite,FMT='(A)') '       DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)		' 
WRITE(nwrite,FMT='(A)') '       DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS) 	' 
WRITE(nwrite,FMT='(A)') '       DOUBLE PRECISION , INTENT(OUT) :: JacC(maxblock_size,NGAS,NGAS) ' 
WRITE(nwrite,FMT='(A)') '       								' 
WRITE(nwrite,FMT='(A)') '       DOUBLE PRECISION :: dw(maxblock_size,nr,NGAS)			' 
WRITE(nwrite,FMT='(A)') '       INTEGER :: ijk							' 

WRITE(nwrite,300)
WRITE(nwrite,637)
637  FORMAT('        JacC=0.d0')
WRITE(nwrite,300)
WRITE(nwrite,640)
640  FORMAT('      CALL dratedc(rk,y,dw,ngas,ijkbeg,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbeg,ijkend'


!-------------------------------------------------------------------------------------------

!     Routine fexloss.f90
nficloss=ipiste
ipiste=ipiste+1
OPEN(nficloss,FILE='chem_spack_fexloss.f90',STATUS='new')
nwrite=nficloss
WRITE(nwrite,FMT='(A)') '  '
!srf - for modules format
WRITE(nwrite,6101)
6101  FORMAT(1X,'MODULE mod_chem_spack_fexloss')
WRITE(nwrite,FMT='(A)') '  '
write(nwrite,6003)
WRITE(nwrite,6004)
WRITE(nwrite,6105)
6105 FORMAT(3X,'PUBLIC :: fexloss ! subroutine')
WRITE(nwrite,6006)

WRITE(nwrite,FMT='(A)') '  '

WRITE(nwrite,701)
701  FORMAT(3X,'SUBROUTINE fexloss(dw,loss,ngas,ijkbegin,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,502)
!     502  format('!',5x,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,703)
703  FORMAT('!',5X,'This routine computes the chemical loss ',  &
    ' term L in a P-Lc formulation.')
WRITE(nwrite,504)
!     504  format('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,505)
!     505  format('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,607)
!     607  format('!     DW: derivative of reaction rates wrt Y.')
WRITE(nwrite,150)
WRITE(nwrite,513)
!     513  format('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,514)
!     514  format('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,715)
715  FORMAT('!     LOSS: array of chemical loss terms.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,516)
!     516  format('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,517)
!     517  format('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,518)
!     518  format('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,519)
!     519  format('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,300)
!      write(nwrite,520)
!     520  format('      implicit none')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '       IMPLICIT NONE'
WRITE(nwrite,300)

!WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: NGAS,ijkbegin,ijkend,maxblock_size,nr'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(IN)  :: dw(maxblock_size,nr,NGAS)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION, INTENT(OUT) :: loss(maxblock_size,NGAS)'
!WRITE(nwrite,FMT='(A)') '      INTEGER :: ijk'

WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: NGAS	                    '			     
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: ijkbegin		    '
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: ijkend			    '
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: maxblock_size		    '
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: nr		 	    '
WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION , INTENT(IN)  :: dw(maxblock_size,nr,NGAS)   '
WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION , INTENT(OUT) :: loss(maxblock_size,NGAS)    '
WRITE(nwrite,FMT='(A)') '     INTEGER :: ijk						    '

WRITE(nwrite,FMT='(A)') ''
WRITE(nwrite,FMT='(A)') '       loss=0.d0'

WRITE(nwrite,300)
WRITE(nwrite,741)
741  FORMAT('!     Chemical loss terms.')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbegin,ijkend'

!--------------------------------------------------------------------------------
!     Routine fexprod.f90
nficprod=ipiste
ipiste=ipiste+1
OPEN(nficprod,FILE='chem_spack_fexprod.f90',STATUS='new')
nwrite=nficprod
WRITE(nwrite,FMT='(A)') '  '

!srf - for modules format
WRITE(nwrite,6201)
6201  FORMAT(1X,'MODULE mod_chem_spack_fexprod')
WRITE(nwrite,FMT='(A)') '  '
write(nwrite,6003)
WRITE(nwrite,6004)
WRITE(nwrite,6205)
6205 FORMAT(3X,'PUBLIC :: fexprod ! subroutine')
WRITE(nwrite,6006)


WRITE(nwrite,FMT='(A)') '  '

WRITE(nwrite,801)
801  FORMAT(3X,'SUBROUTINE fexprod(w,prod,ngas,ijkbegin,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,502)
!     502  format('!',5x,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,803)
803  FORMAT('!',5X,'This routine computes the production ',  &
    ' term P in a P-Lc formulation.')
WRITE(nwrite,504)
!     504  format('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,505)
!     505  format('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,507)
!     507  format('!     W: reaction rates.')
WRITE(nwrite,150)
WRITE(nwrite,513)
!     513  format('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,514)
!     514  format('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,815)
815  FORMAT('!     PROD: array of chemical production terms.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,516)
!     516  format('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,517)
!     517  format('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,518)
!     518  format('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,519)
!     519  format('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,300)
!      write(nwrite,520)
!     520  format('      implicit none')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '       IMPLICIT NONE'

WRITE(nwrite,300)

!WRITE(nwrite,FMT='(A)') '  INTEGER,INTENT(IN) :: ngas,ijkbegin,ijkend,maxblock_size,nr'
!WRITE(nwrite,FMT='(A)') '  DOUBLE PRECISION,INTENT(IN) :: w(maxblock_size,nr)'
!WRITE(nwrite,FMT='(A)') '  DOUBLE PRECISION,INTENT(OUT) :: prod(maxblock_size,NGAS)'
!WRITE(nwrite,FMT='(A)') '  INTEGER :: ijk'

WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ngas                      ' 
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ijkbegin		   ' 
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ijkend 		   ' 
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: maxblock_size		   ' 
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: nr		      	   ' 
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(IN)  :: w(maxblock_size,nr)	   ' 
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(OUT) :: prod(maxblock_size,NGAS)  ' 
WRITE(nwrite,FMT='(A)') '      INTEGER :: ijk						   ' 

WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '       prod=0.d0'
WRITE(nwrite,300)
WRITE(nwrite,841)
841  FORMAT('!     Chemical production terms.')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbegin,ijkend'

!--------------------------------------------------------------------------------
!     Routine rates.f90
nficw=ipiste
ipiste=ipiste+1
OPEN(nficw,FILE='chem_spack_rates.f90',STATUS='new')
nwrite=nficw
WRITE(nwrite,FMT='(A)') '  '

!srf - for modules format
WRITE(nwrite,6301)
6301  FORMAT(1X,'MODULE mod_chem_spack_rates')
WRITE(nwrite,FMT='(A)') '  '
write(nwrite,6003)
WRITE(nwrite,6004)
WRITE(nwrite,6305)
6305 FORMAT(3X,'PUBLIC :: rates ! subroutine')
WRITE(nwrite,6006)


WRITE(nwrite,FMT='(A)') '  '

WRITE(nwrite,901)
901  FORMAT(3X,'SUBROUTINE rates(rk,y,w,ngas,ijkbeg,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,502)
!     502  format('!',5x,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,902)
902  FORMAT('!',5X,'This routine computes the reaction rates.')
WRITE(nwrite,504)
!     504  format('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,505)
!     505  format('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,903)
903  FORMAT('!     RK: kinetic rates.')
WRITE(nwrite,506)
!     506  format('!     Y: chemical concentrations.')
WRITE(nwrite,150)
WRITE(nwrite,513)
!     513  format('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,514)
!     514  format('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,507)
!     507  format('!     W: reaction rates.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,516)
!     516  format('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,517)
!     517  format('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,518)
!     518  format('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,519)
!     519  format('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,300)
      write(nwrite,520)
     520  format('      IMPLICIT NONE')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,300)
!WRITE(nwrite,FMT='(A)') '      INTEGER,INTENT(IN) :: ngas,ijkbeg,ijkend,maxblock_size,nr'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(IN) :: rk(maxblock_size,nr),y(maxblock_size,NGAS)'
!WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION,INTENT(OUT) :: w(maxblock_size,nr)'
!WRITE(nwrite,FMT='(A)') '      INTEGER :: ijk'


WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ngas	               '	   
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ijkbeg 	       '   
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: ijkend 	       '   
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: maxblock_size	       '   
WRITE(nwrite,FMT='(A)') '      INTEGER  	, INTENT(IN)  :: nr		       '   
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)  '   
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS) '   
WRITE(nwrite,FMT='(A)') '      DOUBLE PRECISION , INTENT(OUT) :: w(maxblock_size,nr)   '   
WRITE(nwrite,FMT='(A)') '      INTEGER  	              :: ijk		       '   

!     write(nwrite,537)
!     537  format('      integer i')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '      DO ijk=ijkbeg,ijkend'

!-----------------------------------------------------------------------------
!     Routine dratedc.f
nficdw=ipiste
ipiste=ipiste+1
OPEN(nficdw,FILE='chem_spack_dratedc.f90',STATUS='new')
nwrite=nficdw
WRITE(nwrite,FMT='(A)') '  '


!srf - for modules format
WRITE(nwrite,6401)
6401  FORMAT(1X,'MODULE mod_chem_spack_dratedc')
WRITE(nwrite,FMT='(A)') '  '
write(nwrite,6003)
WRITE(nwrite,6004)
WRITE(nwrite,6405)
6405 FORMAT(3X,'PUBLIC :: dratedc ! subroutine')
WRITE(nwrite,6006)

WRITE(nwrite,FMT='(A)') '  '

WRITE(nwrite,910)
910  FORMAT(3X,'SUBROUTINE dratedc(rk,y,dw,ngas,ijkbeg,ijkend,maxblock_size,nr)')
WRITE(nwrite,300)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,502)
!     502  format('!',5x,'-- DESCRIPTION')
WRITE(nwrite,150)
WRITE(nwrite,911)
911  FORMAT('!',5X,'This routine computes the derivative of reaction ',  &
    ' rates.')
WRITE(nwrite,504)
!     504  format('!     This routine is automatically generated by SPACK.')
WRITE(nwrite,250)filemeca
WRITE(nwrite,251)filespecies
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,505)
!     505  format('!     -- INPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,903)
!     903  format('!     RK: kinetic rates.')
WRITE(nwrite,506)
!     506  format('!     Y: chemical concentrations.')
WRITE(nwrite,150)
WRITE(nwrite,513)
!     513  format('!     -- INPUT/OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,514)
!     514  format('!     -- OUTPUT VARIABLES')
WRITE(nwrite,150)
WRITE(nwrite,607)
!     607  format('!     DW: derivative of reaction rates wrt Y.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,516)
!     516  format('!     -- REMARKS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,517)
!     517  format('!     -- MODIFICATIONS')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,150)
WRITE(nwrite,518)
!     518  format('!     -- AUTHOR(S)')
WRITE(nwrite,150)
WRITE(nwrite,519)
!     519  format('!     SPACK.')
WRITE(nwrite,150)
WRITE(nwrite,200)
WRITE(nwrite,300)
      write(nwrite,520)
     !520  format('      IMPLICIT NONE')
WRITE(nwrite,300)
WRITE(nwrite,300)
WRITE(nwrite,300)

!WRITE(nwrite,FMT='(A)') '     INTEGER,INTENT(IN) :: ngas,ijkbeg,ijkend,maxblock_size,nr'			        
!WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION,INTENT(IN) :: rk(maxblock_size,nr),y(maxblock_size,NGAS) '
!WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION,INTENT(OUT) :: dw(maxblock_size,nr,NGAS) '	        
!WRITE(nwrite,FMT='(A)') '     INTEGER :: ijk'							        
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: ngas                      '			    
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: ijkbeg			  '
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: ijkend			  '
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: maxblock_size		  '
WRITE(nwrite,FMT='(A)') '     INTEGER	       , INTENT(IN)  :: nr			  '
WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION , INTENT(IN)  :: rk(maxblock_size,nr)	  '
WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION , INTENT(IN)  :: y(maxblock_size,NGAS) 	  '
WRITE(nwrite,FMT='(A)') '     DOUBLE PRECISION , INTENT(OUT) :: dw(maxblock_size,nr,NGAS) '
WRITE(nwrite,FMT='(A)') '     INTEGER :: ijk						  '

!     write(nwrite,537)
!     537  format('      integer i')
WRITE(nwrite,300)
WRITE(nwrite,FMT='(A)') '     DO ijk=ijkbeg,ijkend'
!     File non_zero.dat
nficnz=ipiste
ipiste=ipiste+1
OPEN(nficnz,FILE='non_zero.dat',STATUS='new')
WRITE(nwrite,FMT='(A)') '  '
WRITE(nwrite,FMT='(A)') '  '

150  FORMAT('!',6X,a65)
200  FORMAT('!-----------------------------------',  &
    '-------------------------------------')
300  FORMAT(' ')

111  FORMAT('!      INCLUDE FILES only for CATT-BRAMS!!!! ')
222  FORMAT('      INCLUDE ''PARAMETRE'' ')
333  FORMAT('      INCLUDE ''FICCOM'' ')
555  FORMAT('      INCLUDE ''TUV.H'' ')


RETURN
END SUBROUTINE write_header
!------------------------------------------------------------------------

SUBROUTINE write_end
!------------------------------------------------------------------------

!     -- DESCRIPTION

!     Write end of subroutines fexchem.f90, jacdchemdc.f90 and kinetic.f90.
!------------------------------------------------------------------------

!     -- INPUT VARIABLES

!     -- INPUT/OUTPUT VARIABLES

!     -- OUTPUT VARIABLES

!------------------------------------------------------------------------

!     -- REMARKS

!     Label 300: blank line.
!     Label 150: comments.
!     Label 200: C-------...
!------------------------------------------------------------------------

!     -- MODIFICATIONS

!------------------------------------------------------------------------

!     -- AUTHOR(S)

!     Bruno Sportisse, CEREA, 2003.

!------------------------------------------------------------------------
INCLUDE 'nficfort'

!     Routine fexchem.f90
nwrite=nficf

WRITE(nwrite,FMT='(A)') '      END DO'
WRITE(nwrite,300)
WRITE(nwrite,101)
101  FORMAT('!     Volumic source terms.')
WRITE(nwrite,300)
!WRITE(nwrite,FMT='(A)') '        IF(LSOURC)THEN'
!WRITE(nwrite,FMT='(A)') '         chem=chem+ZCsourc'
!WRITE(nwrite,FMT='(A)') '      END IF'
  CALL write_end2(nwrite)
!     Routine kinetic.f90
  nwrite=nfick
  CALL write_end2(nwrite)
  
!     Routine jacdchemdc.f90
  nwrite=nficj
  CALL write_end2(nwrite)
  
!     Routine fexloss.f90
  nwrite=nficloss
  CALL write_end2(nwrite)
  
!     Routine fexprod.f90
  nwrite=nficprod
  CALL write_end2(nwrite)
  
!     Routine rates.f90
  nwrite=nficw
  CALL write_end2(nwrite)
  
!     Routine dratedc.f90
  nwrite=nficdw
  CALL write_end2(nwrite)
  
  
  
  150  FORMAT('!',6X,a65)
  200  FORMAT('!-----------------------------------',  &
      '-------------------------------------')
  300  FORMAT(' ')
  110  FORMAT(6X,'END SUBROUTINE')
  
  RETURN
END SUBROUTINE write_end

SUBROUTINE write_end2(nwrite)
  INCLUDE 'nficfort'

 INTEGER, INTENT(IN)                  :: nwrite
 CHARACTER(LEN=10) :: cnsub

 IF(nwrite==nficdw) cnsub='dratedc'
 IF(nwrite==nficw) cnsub='rates'
 IF(nwrite==nficprod) cnsub='fexprod'
 IF(nwrite==nficloss) cnsub='fexloss'
 IF(nwrite==nficj) cnsub='jacdchemdc'
 IF(nwrite==nfick) cnsub='kinetic'
 IF(nwrite==nficf) cnsub='fexchem' 

 IF(nwrite==nfick)  WRITE(nwrite,FMT='(A)') '       END DO'
 IF(nwrite==nficj)  WRITE(nwrite,FMT='(A)') '       END DO'
 IF(nwrite==nficw)  WRITE(nwrite,FMT='(A)') '       END DO'
 IF(nwrite==nficdw) WRITE(nwrite,FMT='(A)') '       END DO'
 IF(nwrite==nficprod) WRITE(nwrite,FMT='(A)') '      END DO'
 IF(nwrite==nficloss) WRITE(nwrite,FMT='(A)') '      END DO'
 WRITE(nwrite,300)
 WRITE(nwrite,FMT='(A)') '   END SUBROUTINE '//trim(cnsub)
 WRITE(nwrite,300)
 WRITE(nwrite,FMT='(A)') '  END MODULE mod_chem_spack_'//trim(cnsub)
 WRITE(nwrite,300)

150  FORMAT('!',6X,a65)
200  FORMAT('!-----------------------------------',  &
    '-------------------------------------')
300  FORMAT(' ')

END SUBROUTINE write_end2














